[package]
name = "puchiprop_cases"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puchiprop_core = { workspace = true }
rand = { workspace = true }
